version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: Europe/London
    open-pull-requests-limit: 10
    groups:
      dotnet-test-dependencies:
        patterns:
          - "Microsoft.NET.Test.Sdk"
          - "xunit*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: Europe/London
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
