using System.Text.Json.Nodes;
using WastelandForge.Generation;

namespace WastelandForge.UnitTests;

public sealed class XEditAuditAdapterPlannerTests
{
    [Fact]
    public void PlanReturnsEvidenceOnlyXEditAuditEntries()
    {
        var projectRoot = Path.Combine(RepositoryRoot(), "fixtures", "projects", "XEditAuditExample");

        var result = new XEditAuditAdapterPlanner().Plan(projectRoot);

        Assert.False(result.HasErrors);
        Assert.Equal(Path.GetFullPath(projectRoot), result.ProjectRoot);
        Assert.Equal(XEditAuditAdapterPlanner.Target, result.Target);
        Assert.Equal("io.github.theboyyss.xeditauditexample", result.ProjectId?.ToString());
        var audit = Assert.Single(result.Audits);
        Assert.Equal("io.github.theboyyss.xeditauditexample.xedit_audits.record_inspection", audit.AuditId);
        Assert.Equal("record-inspection", audit.Intent);
        Assert.Equal("script-report-evidence", audit.Mode);
        Assert.Equal("pascal", audit.ScriptLanguage);
        Assert.Equal("json", audit.ReportFormat);
        Assert.Equal(new[] { "QUST", "DIAL" }, audit.RecordTypes);
        Assert.Equal(new[] { "tool.xedit.record_inspection" }, audit.RequiredCapabilities);
        var plugin = Assert.Single(audit.TargetPlugins);
        Assert.Equal("SyntheticAuditSubject.esp", plugin.Name);
        Assert.Equal("subject", plugin.Role);
        Assert.Equal("generated/xedit-audit/scripts/synthetic-record-inspection.pas", audit.ScriptPath);
        Assert.Equal("generated/xedit-audit/reports/synthetic-record-inspection.json", audit.ReportPath);
        Assert.False(audit.ExecutesXEdit);
        Assert.False(audit.MutatesPlugins);
        Assert.False(audit.WritesPatches);
        Assert.False(audit.UsesRealPluginFixture);
        Assert.Equal("src/registries/xedit-audit/main.json", audit.Source.File);
        Assert.Equal("/audits/0", audit.Source.Pointer?.ToString());
        Assert.False(File.Exists(Path.Combine(projectRoot, audit.ScriptPath.Replace('/', Path.DirectorySeparatorChar))));
        Assert.False(File.Exists(Path.Combine(projectRoot, audit.ReportPath.Replace('/', Path.DirectorySeparatorChar))));
    }

    [Fact]
    public void PlanStopsBeforeEntriesWhenValidationHasErrors()
    {
        var projectRoot = Path.Combine(
            RepositoryRoot(),
            "fixtures",
            "projects",
            "BrokenCases",
            "MissingXEditAuditRecordInspectionRequirement");

        var result = new XEditAuditAdapterPlanner().Plan(projectRoot);

        Assert.True(result.HasErrors);
        Assert.Empty(result.Audits);
        Assert.Contains(result.Diagnostics.Issues, issue => issue.RuleId.ToString() == "WF-SEM-044");
    }

    [Fact]
    public void EmitWritesScaffoldScriptsUnderGeneratedRootOnly()
    {
        var projectRoot = CopyFixtureProject("XEditAuditExample");

        var result = new XEditAuditScriptScaffoldEmitter().Emit(projectRoot);

        Assert.False(result.HasErrors);
        Assert.Equal(XEditAuditScriptScaffoldEmitter.Target, result.Target);
        var document = Assert.Single(result.Documents);
        var generatedFile = Assert.Single(result.GeneratedFiles);
        Assert.Equal("io.github.theboyyss.xeditauditexample.xedit_audits.record_inspection", document.AuditId);
        Assert.Equal("generated/xedit-audit/scripts/synthetic-record-inspection.pas", document.ScriptPath);
        Assert.Equal("generated/xedit-audit/reports/synthetic-record-inspection.json", document.ExpectedReportPath);
        Assert.Equal("lf", document.LineEnding);
        Assert.Equal("utf-8", document.Encoding);
        Assert.Equal(document.AuditId, generatedFile.AuditId);
        Assert.Equal(document.ScriptPath, generatedFile.OutputPath);
        Assert.Equal(document.ExpectedReportPath, generatedFile.ExpectedReportPath);
        Assert.Equal(document.ContentBytes, generatedFile.ContentBytes);
        var scriptPath = Path.Combine(projectRoot, document.ScriptPath.Replace('/', Path.DirectorySeparatorChar));
        Assert.True(File.Exists(scriptPath));
        var content = File.ReadAllText(scriptPath);
        Assert.Equal(document.Content, content);
        Assert.Contains("Generated by WastelandForge.", content, StringComparison.Ordinal);
        Assert.Contains("WastelandForge xEdit audit scaffold", content, StringComparison.Ordinal);
        Assert.Contains("Target plugin: SyntheticAuditSubject.esp (subject)", content, StringComparison.Ordinal);
        Assert.Contains("Record type: QUST", content, StringComparison.Ordinal);
        Assert.Contains("Record type: DIAL", content, StringComparison.Ordinal);
        Assert.Contains("Required capability: tool.xedit.record_inspection", content, StringComparison.Ordinal);
        Assert.Contains("Gate 219 does not execute xEdit", content, StringComparison.Ordinal);
        Assert.DoesNotContain("\r", content, StringComparison.Ordinal);
        Assert.Equal("generated/xedit-audit/xedit-audit-script-manifest.json", result.ManifestPath);
        Assert.Equal("generated/xedit-audit/checksums.sha256", result.ChecksumsPath);
        Assert.Contains(result.OutputDigests, digest => digest.Path == document.ScriptPath && digest.Length == document.ContentBytes);
        Assert.Contains(result.OutputDigests, digest => digest.Path == result.ManifestPath);
        Assert.DoesNotContain(result.OutputDigests, digest => digest.Path == result.ChecksumsPath);
        var manifestPath = Path.Combine(projectRoot, result.ManifestPath!.Replace('/', Path.DirectorySeparatorChar));
        Assert.True(File.Exists(manifestPath));
        var manifest = JsonNode.Parse(File.ReadAllText(manifestPath))?.AsObject()
            ?? throw new InvalidOperationException("xEdit audit script manifest did not parse.");
        Assert.Equal("wastelandforge.xedit-audit-script-manifest", (string?)manifest["kind"]);
        Assert.Equal("wastelandforge/xedit-audit-script/v0-skeleton", (string?)manifest["manifestType"]);
        Assert.Equal("xedit-audit", (string?)manifest["target"]);
        Assert.Equal("generated/xedit-audit", (string?)manifest["root"]);
        Assert.Equal("io.github.theboyyss.xeditauditexample", (string?)manifest["project"]?["id"]);
        Assert.Equal(false, (bool?)manifest["execution"]?["executesXEdit"]);
        Assert.Equal(false, (bool?)manifest["execution"]?["parsesReports"]);
        Assert.Equal(false, (bool?)manifest["execution"]?["generatesPatches"]);
        Assert.Equal(false, (bool?)manifest["execution"]?["mutatesPlugins"]);
        Assert.Equal(false, (bool?)manifest["execution"]?["writesGameData"]);
        Assert.Equal("io.github.theboyyss.xeditauditexample.xedit_audits.record_inspection", (string?)manifest["scaffolds"]?[0]?["id"]);
        Assert.Equal(document.ScriptPath, (string?)manifest["scaffolds"]?[0]?["scriptPath"]);
        Assert.Equal(document.ExpectedReportPath, (string?)manifest["scaffolds"]?[0]?["expectedReportPath"]);
        Assert.Equal("QUST", (string?)manifest["scaffolds"]?[0]?["recordTypes"]?[0]);
        Assert.Equal("tool.xedit.record_inspection", (string?)manifest["scaffolds"]?[0]?["requiredCapabilities"]?[0]);
        Assert.Equal(document.ScriptPath, (string?)manifest["outputs"]?[0]?["path"]);
        Assert.Equal(document.ContentBytes, (long?)manifest["outputs"]?[0]?["length"]);
        var checksumsPath = Path.Combine(projectRoot, result.ChecksumsPath!.Replace('/', Path.DirectorySeparatorChar));
        Assert.True(File.Exists(checksumsPath));
        var checksums = File.ReadAllText(checksumsPath);
        Assert.Contains("  scripts/synthetic-record-inspection.pas", checksums, StringComparison.Ordinal);
        Assert.Contains("  xedit-audit-script-manifest.json", checksums, StringComparison.Ordinal);
        Assert.DoesNotContain("reports/", checksums, StringComparison.Ordinal);
        Assert.DoesNotContain("Data/", checksums, StringComparison.Ordinal);
        Assert.False(File.Exists(Path.Combine(projectRoot, document.ExpectedReportPath.Replace('/', Path.DirectorySeparatorChar))));
        Assert.False(Directory.Exists(Path.Combine(projectRoot, "Data")));
    }

    [Fact]
    public void EmitStopsBeforeWritingWhenValidationHasErrors()
    {
        var projectRoot = CopyFixtureProject(Path.Combine("BrokenCases", "MissingXEditAuditRecordInspectionRequirement"));

        var result = new XEditAuditScriptScaffoldEmitter().Emit(projectRoot);

        Assert.True(result.HasErrors);
        Assert.Empty(result.PlanEntries);
        Assert.Empty(result.Documents);
        Assert.Empty(result.GeneratedFiles);
        Assert.Null(result.ManifestPath);
        Assert.Null(result.ChecksumsPath);
        Assert.Empty(result.OutputDigests);
        Assert.Contains(result.Diagnostics.Issues, issue => issue.RuleId.ToString() == "WF-SEM-044");
        Assert.False(Directory.Exists(Path.Combine(projectRoot, "generated")));
        Assert.False(Directory.Exists(Path.Combine(projectRoot, "Data")));
    }

    [Fact]
    public void ParseReadsSyntheticReportFixtureWithoutExecutingXEdit()
    {
        var projectRoot = CopyFixtureProject("XEditAuditExample");
        CopySyntheticReportFixture(projectRoot);

        var result = new XEditAuditReportParser().Parse(projectRoot);

        Assert.False(result.HasErrors);
        Assert.Equal(XEditAuditReportParser.Target, result.Target);
        Assert.Equal("io.github.theboyyss.xeditauditexample", result.ProjectId?.ToString());
        var report = Assert.Single(result.Reports);
        Assert.Equal("io.github.theboyyss.xeditauditexample.xedit_audits.record_inspection", report.AuditId);
        Assert.Equal("generated/xedit-audit/reports/synthetic-record-inspection.json", report.ReportPath);
        Assert.Equal(XEditAuditReportParser.ReportKind, report.Kind);
        Assert.Equal("record-inspection", report.Intent);
        Assert.Equal("json", report.ReportFormat);
        Assert.True(report.Synthetic);
        Assert.False(report.UsesRealPluginFixture);
        Assert.False(report.Safety.ExecutesXEdit);
        Assert.False(report.Safety.MutatesPlugins);
        Assert.False(report.Safety.WritesPatches);
        Assert.Equal(2, report.Summary.Records);
        Assert.Equal(2, report.Summary.Findings);
        Assert.Equal(0, report.Summary.ErrorFindings);
        Assert.Equal(1, report.Summary.WarningFindings);
        Assert.Equal(1, report.Summary.NoteFindings);
        Assert.Contains(report.Records, record =>
            record.Plugin == "SyntheticAuditSubject.esp" &&
            record.RecordType == "QUST" &&
            record.EditorId == "SyntheticQuest");
        Assert.Contains(report.Findings, finding =>
            finding.Id == "synthetic.dialogue.inspectable" &&
            finding.Severity == "warning" &&
            finding.RecordType == "DIAL");
        Assert.False(File.Exists(Path.Combine(projectRoot, "generated", "xedit-audit", "scripts", "synthetic-record-inspection.pas")));
        Assert.False(File.Exists(Path.Combine(projectRoot, "generated", "xedit-audit", "xedit-audit-script-manifest.json")));
        Assert.False(File.Exists(Path.Combine(projectRoot, "generated", "xedit-audit", "checksums.sha256")));
        Assert.False(Directory.Exists(Path.Combine(projectRoot, "Data")));
    }

    [Fact]
    public void ParseReportsMissingSyntheticReportAsDiagnostic()
    {
        var projectRoot = CopyFixtureProject("XEditAuditExample");

        var result = new XEditAuditReportParser().Parse(projectRoot);

        Assert.True(result.HasErrors);
        Assert.Empty(result.Reports);
        var issue = Assert.Single(result.Diagnostics.Issues, issue => issue.RuleId.ToString() == XEditAuditReportParser.ReportParserRuleId);
        Assert.Equal("xEdit audit report is missing", issue.Title);
        Assert.Equal("generated/xedit-audit/reports/synthetic-record-inspection.json", issue.PrimaryLocation.File);
        Assert.False(Directory.Exists(Path.Combine(projectRoot, "generated")));
        Assert.False(Directory.Exists(Path.Combine(projectRoot, "Data")));
    }

    [Fact]
    public void ParseReportsMalformedSyntheticReportAsDiagnostic()
    {
        var projectRoot = CopyFixtureProject("XEditAuditExample");
        WriteSyntheticReport(projectRoot, "{ not valid json");

        var result = new XEditAuditReportParser().Parse(projectRoot);

        Assert.True(result.HasErrors);
        Assert.Empty(result.Reports);
        var issue = Assert.Single(result.Diagnostics.Issues, issue => issue.RuleId.ToString() == XEditAuditReportParser.ReportParserRuleId);
        Assert.Equal("xEdit audit report JSON is invalid", issue.Title);
        Assert.Equal("generated/xedit-audit/reports/synthetic-record-inspection.json", issue.PrimaryLocation.File);
        Assert.False(File.Exists(Path.Combine(projectRoot, "generated", "xedit-audit", "scripts", "synthetic-record-inspection.pas")));
        Assert.False(Directory.Exists(Path.Combine(projectRoot, "Data")));
    }

    private static void CopySyntheticReportFixture(string projectRoot)
    {
        var source = Path.Combine(RepositoryRoot(), "fixtures", "xedit-audit-reports", "synthetic-record-inspection.json");
        var target = SyntheticReportPath(projectRoot);
        Directory.CreateDirectory(Path.GetDirectoryName(target) ?? projectRoot);
        File.Copy(source, target, overwrite: true);
    }

    private static void WriteSyntheticReport(string projectRoot, string content)
    {
        var target = SyntheticReportPath(projectRoot);
        Directory.CreateDirectory(Path.GetDirectoryName(target) ?? projectRoot);
        File.WriteAllText(target, content);
    }

    private static string SyntheticReportPath(string projectRoot) =>
        Path.Combine(projectRoot, "generated", "xedit-audit", "reports", "synthetic-record-inspection.json");

    private static string CopyFixtureProject(string name)
    {
        var source = Path.Combine(RepositoryRoot(), "fixtures", "projects", name);
        var target = Path.Combine(Path.GetTempPath(), "WastelandForge.Tests", Guid.NewGuid().ToString("N"), name);
        CopyDirectory(source, target);
        return target;
    }

    private static void CopyDirectory(string source, string target)
    {
        Directory.CreateDirectory(target);
        foreach (var directory in Directory.EnumerateDirectories(source, "*", SearchOption.AllDirectories))
        {
            Directory.CreateDirectory(Path.Combine(target, Path.GetRelativePath(source, directory)));
        }

        foreach (var file in Directory.EnumerateFiles(source, "*", SearchOption.AllDirectories))
        {
            var destination = Path.Combine(target, Path.GetRelativePath(source, file));
            Directory.CreateDirectory(Path.GetDirectoryName(destination) ?? target);
            File.Copy(file, destination, overwrite: true);
        }
    }

    private static string RepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);
        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "WastelandForge.sln")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("Could not locate repository root.");
    }
}
