<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="JsonSchema.Net" Version="9.2.2" />
    <PackageReference Include="YamlDotNet" Version="18.0.0" />
    <ProjectReference Include="..\WastelandForge.Core\WastelandForge.Core.csproj" />
    <ProjectReference Include="..\WastelandForge.Schema\WastelandForge.Schema.csproj" />
    <ProjectReference Include="..\WastelandForge.Registry\WastelandForge.Registry.csproj" />
  </ItemGroup>

</Project>
