<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WastelandForge.Core\WastelandForge.Core.csproj" />
    <ProjectReference Include="..\WastelandForge.Registry\WastelandForge.Registry.csproj" />
    <ProjectReference Include="..\WastelandForge.Provenance\WastelandForge.Provenance.csproj" />
  </ItemGroup>

</Project>
