<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\WastelandForge.Core\WastelandForge.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\schemas\**\*.json" Link="schemas\%(RecursiveDir)%(Filename)%(Extension)" />
    <None Include="..\..\schemas\**\*.json" Pack="true" PackagePath="schemas\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
