<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\WastelandForge.Core\WastelandForge.Core.csproj" />
    <ProjectReference Include="..\..\src\WastelandForge.Cli\WastelandForge.Cli.csproj" />
    <ProjectReference Include="..\..\src\WastelandForge.Generation\WastelandForge.Generation.csproj" />
  </ItemGroup>

</Project>
