using System.Text.Json.Nodes;
using WastelandForge.Cli;
using WastelandForge.Desktop;

namespace WastelandForge.WindowsTests;

public sealed class QuestPresentationRevisionAuthoringTests
{
    [Fact]
    public void RevisesOnlyPresentationAndEmitsThreeWorklists()
    {
        var root = CopyExample(); try { var load = QuestPresentationRevisionAuthoring.Load(root); Assert.True(load.Success, load.Message); var q = load.Quests.Single(); var s = load.Stages.First(); var o = load.Objectives.Single(); var input = new QuestRevisionInput(q.Id, s.Id, o.Id, "Revised Quest", "Revised summary.", "Revised Stage", "Revised stage summary.", "Revised objective."); var path = Quest(root); var bytes = File.ReadAllBytes(path); var before = JsonNode.Parse(File.ReadAllText(path))!; var preview = QuestPresentationRevisionAuthoring.Preview(root, input); Assert.True(preview.Success, preview.Message); Assert.Equal(bytes, File.ReadAllBytes(path)); Assert.True(QuestPresentationRevisionAuthoring.Apply(root, input, preview.Token!).Success); Assert.Equal(0, ForgeCli.Run(["validate", root, "--format", "json", "--no-input"])); Assert.Equal(0, ForgeCli.Run(["package", root, "--target", "geck-handoff", "--format", "json", "--no-input"])); var after = JsonNode.Parse(File.ReadAllText(path))!; var original = before["quests"]![0]!.DeepClone().AsObject(); var revised = after["quests"]![0]!.DeepClone().AsObject(); original.Remove("title"); original.Remove("summary"); revised.Remove("title"); revised.Remove("summary"); var os = original["stages"]!.AsArray().Single(x => x!["id"]!.GetValue<string>() == s.Id)!.AsObject(); var rs = revised["stages"]!.AsArray().Single(x => x!["id"]!.GetValue<string>() == s.Id)!.AsObject(); os.Remove("title"); os.Remove("summary"); rs.Remove("title"); rs.Remove("summary"); var oo = original["objectives"]!.AsArray().Single()!.AsObject(); var ro = revised["objectives"]!.AsArray().Single()!.AsObject(); oo.Remove("text"); ro.Remove("text"); Assert.True(JsonNode.DeepEquals(original, revised)); var work = Path.Combine(root, "dist", "geck-handoff", "worklists"); Assert.Contains("Revised Quest", File.ReadAllText(Path.Combine(work, "quests.tsv"))); Assert.Contains("Revised Stage", File.ReadAllText(Path.Combine(work, "quest-stages.tsv"))); Assert.Contains("Revised objective.", File.ReadAllText(Path.Combine(work, "quest-objectives.tsv"))); Assert.False(QuestPresentationRevisionAuthoring.Preview(root, input).Success); } finally { Directory.Delete(root, true); }
    }
    [Fact]
    public void RefusesBlankWrongOwnerAndStaleInput()
    {
        var root = CopyExample(); try { var load = QuestPresentationRevisionAuthoring.Load(root); var q = load.Quests.Single(); var s = load.Stages.First(); var o = load.Objectives.Single(); Assert.False(QuestPresentationRevisionAuthoring.Preview(root, new(q.Id, s.Id, o.Id, "", "", "", "", "Objective")).Success); Assert.False(QuestPresentationRevisionAuthoring.Preview(root, new(q.Id, "wrong", o.Id, "Quest", "", "", "", "Objective")).Success); var input = new QuestRevisionInput(q.Id, s.Id, o.Id, "Changed", "", "", "", "Objective"); var preview = QuestPresentationRevisionAuthoring.Preview(root, input); var path = Quest(root); File.AppendAllText(path, Environment.NewLine); var changed = File.ReadAllBytes(path); Assert.False(QuestPresentationRevisionAuthoring.Apply(root, input, preview.Token!).Success); Assert.Equal(changed, File.ReadAllBytes(path)); } finally { Directory.Delete(root, true); }
    }
    private static string Quest(string root) => Path.Combine(root, "src", "registries", "quests", "main.json"); private static string CopyExample() { var source = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "../../../../../fixtures/projects/ExampleMod")); var root = Path.Combine(Path.GetTempPath(), "WastelandForge.QuestRevision", Guid.NewGuid().ToString("N")); Copy(source, root); foreach (var file in Directory.GetFiles(root, "*", SearchOption.AllDirectories)) File.SetAttributes(file, FileAttributes.Normal); return root; } private static void Copy(string source, string target) { Directory.CreateDirectory(target); foreach (var file in Directory.GetFiles(source)) File.Copy(file, Path.Combine(target, Path.GetFileName(file))); foreach (var directory in Directory.GetDirectories(source)) if (Path.GetFileName(directory) is not ("dist" or "generated")) Copy(directory, Path.Combine(target, Path.GetFileName(directory))); }
}
