using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using WastelandForge.Validation;

namespace WastelandForge.Desktop;

internal sealed record QuestRevisionChoice(string Id, string OwnerId, string Display, string Title, string Summary, string Text);
internal sealed record QuestRevisionLoadResult(bool Success, string Message, IReadOnlyList<QuestRevisionChoice> Quests, IReadOnlyList<QuestRevisionChoice> Stages, IReadOnlyList<QuestRevisionChoice> Objectives);
internal sealed record QuestRevisionInput(string QuestId, string StageId, string ObjectiveId, string QuestTitle, string QuestSummary, string StageTitle, string StageSummary, string ObjectiveText);
internal sealed record QuestRevisionPreview(bool Success, string Message, string? QuestJson, string? Changes, string? Token);
internal sealed record QuestRevisionResult(bool Success, string Message);

internal static class QuestPresentationRevisionAuthoring
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };
    public static QuestRevisionLoadResult Load(string root)
    {
        try { var (_, quest, _, _, _, _) = Read(root); if (new ProjectValidationPipeline().Validate(root).HasErrors) return FailLoad("Project validation must pass before loading quest presentation choices."); var quests = Arr(quest, "quests"); var q = quests.Select(x => new QuestRevisionChoice(Text(x, "id"), Text(x, "id"), Text(x, "title"), Text(x, "title"), Text(x, "summary"), "")).OrderBy(x => x.Id, StringComparer.Ordinal).ToArray(); var s = quests.SelectMany(owner => Arr(owner, "stages").Select(x => new QuestRevisionChoice(Text(x, "id"), Text(owner, "id"), $"{x["stage"]}: {Text(x, "title")}", Text(x, "title"), Text(x, "summary"), ""))).OrderBy(x => x.Id, StringComparer.Ordinal).ToArray(); var o = quests.SelectMany(owner => Arr(owner, "objectives").Select(x => new QuestRevisionChoice(Text(x, "id"), Text(owner, "id"), Text(x, "text"), "", "", Text(x, "text")))).OrderBy(x => x.Id, StringComparer.Ordinal).ToArray(); return q.Length == 0 ? FailLoad("Quest source has no quests.") : new(true, "Quest presentation choices loaded.", q, s, o); }
        catch (Exception ex) when (ex is IOException or JsonException or InvalidOperationException) { return FailLoad("Quest presentation load failed: " + ex.Message); }
    }
    public static QuestRevisionPreview Preview(string root, QuestRevisionInput input)
    {
        try { var (_, questRoot, _, manifestBytes, questBytes, dialogueBytes) = Read(root); if (new ProjectValidationPipeline().Validate(root).HasErrors) return Fail("Project validation must pass before preview."); var quest = Arr(questRoot, "quests").SingleOrDefault(x => Text(x, "id") == input.QuestId) ?? throw new InvalidOperationException("Selected quest no longer exists."); var stage = Arr(quest, "stages").SingleOrDefault(x => Text(x, "id") == input.StageId) ?? throw new InvalidOperationException("Selected stage does not belong to the selected quest."); var objective = Arr(quest, "objectives").SingleOrDefault(x => Text(x, "id") == input.ObjectiveId) ?? throw new InvalidOperationException("Selected objective does not belong to the selected quest."); var beforeQuest = quest.DeepClone(); var title = input.QuestTitle.Trim(); var objectiveText = input.ObjectiveText.Trim(); if (title.Length == 0) throw new InvalidOperationException("Quest title is required."); if (objectiveText.Length == 0) throw new InvalidOperationException("Objective text is required."); quest["title"] = title; SetOptional(quest, "summary", input.QuestSummary); SetOptional(stage, "title", input.StageTitle); SetOptional(stage, "summary", input.StageSummary); objective["text"] = objectiveText; if (JsonNode.DeepEquals(beforeQuest, quest)) throw new InvalidOperationException("Revision does not change the selected quest presentation."); var proposal = Json(questRoot); var changes = $"quest title: {Text((JsonObject)beforeQuest, "title")} -> {title}\nquest summary: {Text((JsonObject)beforeQuest, "summary")} -> {Text(quest, "summary")}\nstage title: {Text(Arr((JsonObject)beforeQuest, "stages").Single(x => Text(x, "id") == input.StageId), "title")} -> {Text(stage, "title")}\nstage summary: {Text(Arr((JsonObject)beforeQuest, "stages").Single(x => Text(x, "id") == input.StageId), "summary")} -> {Text(stage, "summary")}\nobjective text: {Text(Arr((JsonObject)beforeQuest, "objectives").Single(x => Text(x, "id") == input.ObjectiveId), "text")} -> {objectiveText}"; return new(true, "Quest presentation revision preview ready.", proposal, changes, Hash(manifestBytes + "\n" + questBytes + "\n" + dialogueBytes + "\n" + proposal)); }
        catch (Exception ex) when (ex is IOException or JsonException or InvalidOperationException) { return Fail("Quest presentation preview failed: " + ex.Message); }
    }
    public static QuestRevisionResult Apply(string root, QuestRevisionInput input, string token)
    {
        var preview = Preview(root, input); if (!preview.Success || preview.Token != token) return new(false, preview.Success ? "Source, selection, or inputs changed; preview again." : preview.Message); var path = QuestPath(root); var original = File.ReadAllBytes(path); try { File.WriteAllText(path, preview.QuestJson!, new UTF8Encoding(false)); if (new ProjectValidationPipeline().Validate(root).HasErrors) { File.WriteAllBytes(path, original); return new(false, "Quest presentation revision failed validation; original source restored."); } return new(true, "Quest presentation revised and validated."); } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { try { File.WriteAllBytes(path, original); } catch { } return new(false, "Quest presentation write failed; original source restored: " + ex.Message); }
    }
    private static (JsonObject Manifest, JsonObject Quest, JsonObject Dialogue, string ManifestBytes, string QuestBytes, string DialogueBytes) Read(string root)
    {
        var projectRoot = Path.GetFullPath(root); var mp = Path.Combine(projectRoot, "wastelandforge.json"); var qp = QuestPath(projectRoot); var dp = Path.Combine(projectRoot, "src", "registries", "dialogue", "main.json"); if (!File.Exists(mp) || !File.Exists(qp) || !File.Exists(dp)) throw new InvalidOperationException("Canonical manifest, quest main.json, and dialogue main.json are required."); var mb = File.ReadAllText(mp); var qb = File.ReadAllText(qp); var db = File.ReadAllText(dp); var m = JsonNode.Parse(mb)?.AsObject() ?? throw new JsonException("Manifest is not an object."); if (m["registries"]?["quests"]?.GetValue<string>() != "src/registries/quests/" || m["registries"]?["dialogue"]?.GetValue<string>() != "src/registries/dialogue/") throw new InvalidOperationException("Manifest must use canonical narrative registry paths."); var q = JsonNode.Parse(qb)?.AsObject() ?? throw new JsonException("Quest source is not an object."); var d = JsonNode.Parse(db)?.AsObject() ?? throw new JsonException("Dialogue source is not an object."); if (Text(q, "schemaVersion") != "0.6.0" || Text(d, "schemaVersion") != "0.23.0") throw new InvalidOperationException("Quest 0.6.0 and dialogue 0.23.0 are required."); if (Directory.GetFiles(Path.GetDirectoryName(qp)!).Length != 1 || Directory.GetFiles(Path.GetDirectoryName(dp)!).Length != 1) throw new InvalidOperationException("One main.json document per narrative registry is required."); return (m, q, d, mb, qb, db);
    }
    private static string QuestPath(string root) => Path.Combine(root, "src", "registries", "quests", "main.json"); private static QuestRevisionLoadResult FailLoad(string m) => new(false, m, [], [], []); private static QuestRevisionPreview Fail(string m) => new(false, m, null, null, null); private static IReadOnlyList<JsonObject> Arr(JsonObject o, string k) => o[k] is JsonArray a ? a.OfType<JsonObject>().ToArray() : []; private static string Text(JsonObject? o, string k) => o?[k]?.GetValue<string>() ?? ""; private static void SetOptional(JsonObject o, string k, string v) { var text = v.Trim(); if (text.Length == 0) o.Remove(k); else o[k] = text; } private static string Json(JsonObject o) => o.ToJsonString(JsonOptions) + Environment.NewLine; private static string Hash(string v) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(v))).ToLowerInvariant();
}
