using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using WastelandForge.Validation;

namespace WastelandForge.Desktop;

internal sealed record QuestConditionChoice(string Id, string OwnerId, string Display);
internal sealed record QuestConditionLoadResult(bool Success, string Message, IReadOnlyList<QuestConditionChoice> Quests, IReadOnlyList<QuestConditionChoice> Stages, IReadOnlyList<QuestConditionChoice> Variables);
internal sealed record QuestConditionInput(string QuestId, string Mode, string StageId, string VariableId, string EqualsInteger, string Slug, string Title, string Summary);
internal sealed record QuestConditionPreview(bool Success, string Message, string? QuestJson, string? Declaration, string? Token);
internal sealed record QuestConditionResult(bool Success, string Message);

internal static class QuestConditionAuthoring
{
    public const string StageDone = "Stage Done"; public const string VariableEquals = "Variable Equals"; private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };
    public static QuestConditionLoadResult Load(string root)
    {
        try { var (_, quest, _, _, _, _) = Read(root); if (new ProjectValidationPipeline().Validate(root).HasErrors) return FailLoad("Project validation must pass before loading quest condition choices."); var quests = Arr(quest, "quests"); var q = quests.Select(x => new QuestConditionChoice(Text(x, "id"), Text(x, "id"), Text(x, "title"))).OrderBy(x => x.Id, StringComparer.Ordinal).ToArray(); var s = quests.SelectMany(owner => Arr(owner, "stages").Select(x => new QuestConditionChoice(Text(x, "id"), Text(owner, "id"), $"{x["stage"]}: {Text(x, "title")}"))).OrderBy(x => x.Id, StringComparer.Ordinal).ToArray(); var v = quests.SelectMany(owner => Arr(owner, "variables").Where(x => Text(x, "variableType") == "integer").Select(x => new QuestConditionChoice(Text(x, "id"), Text(owner, "id"), string.IsNullOrWhiteSpace(Text(x, "title")) ? Text(x, "id") : Text(x, "title")))).OrderBy(x => x.Id, StringComparer.Ordinal).ToArray(); return q.Length == 0 ? FailLoad("Quest source has no quests.") : new(true, "Quest condition choices loaded.", q, s, v); } catch (Exception ex) when (ex is IOException or JsonException or InvalidOperationException) { return FailLoad("Quest condition load failed: " + ex.Message); }
    }
    public static QuestConditionPreview Preview(string root, QuestConditionInput input)
    {
        try { var (_, questRoot, _, mb, qb, db) = Read(root); if (new ProjectValidationPipeline().Validate(root).HasErrors) return Fail("Project validation must pass before preview."); var quest = Arr(questRoot, "quests").SingleOrDefault(x => Text(x, "id") == input.QuestId) ?? throw new InvalidOperationException("Selected quest no longer exists."); var id = input.QuestId + ".condition." + Slug(input.Slug); if (Arr(quest, "conditions").Any(x => Text(x, "id") == id)) throw new InvalidOperationException($"Quest condition '{id}' already exists."); JsonObject condition; if (input.Mode == StageDone) { if (!Arr(quest, "stages").Any(x => Text(x, "id") == input.StageId)) throw new InvalidOperationException("Selected stage does not belong to the selected quest."); condition = new JsonObject { ["id"] = id, ["conditionType"] = "stageDone", ["stageId"] = input.StageId }; } else if (input.Mode == VariableEquals) { if (!Arr(quest, "variables").Any(x => Text(x, "id") == input.VariableId && Text(x, "variableType") == "integer")) throw new InvalidOperationException("Selected integer variable does not belong to the selected quest."); if (!int.TryParse(input.EqualsInteger.Trim(), out var equals)) throw new InvalidOperationException("Equals value must be a 32-bit integer."); condition = new JsonObject { ["id"] = id, ["conditionType"] = "variableEquals", ["variableId"] = input.VariableId, ["equalsInteger"] = equals }; } else throw new InvalidOperationException("Select Stage Done or Variable Equals."); Optional(condition, "title", input.Title); Optional(condition, "summary", input.Summary); Ensure(quest, "conditions").Add(condition); var proposal = Json(questRoot); return new(true, "Quest condition preview ready.", proposal, condition.ToJsonString(JsonOptions), Hash(mb + "\n" + qb + "\n" + db + "\n" + proposal)); } catch (Exception ex) when (ex is IOException or JsonException or InvalidOperationException) { return Fail("Quest condition preview failed: " + ex.Message); }
    }
    public static QuestConditionResult Append(string root, QuestConditionInput input, string token) { var preview = Preview(root, input); if (!preview.Success || preview.Token != token) return new(false, preview.Success ? "Source, selection, or inputs changed; preview again." : preview.Message); var path = QuestPath(root); var original = File.ReadAllBytes(path); try { File.WriteAllText(path, preview.QuestJson!, new UTF8Encoding(false)); if (new ProjectValidationPipeline().Validate(root).HasErrors) { File.WriteAllBytes(path, original); return new(false, "Quest condition failed validation; original source restored."); } return new(true, "Quest condition appended and validated."); } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { try { File.WriteAllBytes(path, original); } catch { } return new(false, "Quest condition write failed; original source restored: " + ex.Message); } }
    private static (JsonObject Manifest, JsonObject Quest, JsonObject Dialogue, string ManifestBytes, string QuestBytes, string DialogueBytes) Read(string root) { var r = Path.GetFullPath(root); var mp = Path.Combine(r, "wastelandforge.json"); var qp = QuestPath(r); var dp = Path.Combine(r, "src", "registries", "dialogue", "main.json"); if (!File.Exists(mp) || !File.Exists(qp) || !File.Exists(dp)) throw new InvalidOperationException("Canonical manifest, quest main.json, and dialogue main.json are required."); var mb = File.ReadAllText(mp); var qb = File.ReadAllText(qp); var db = File.ReadAllText(dp); var m = JsonNode.Parse(mb)?.AsObject() ?? throw new JsonException("Manifest is not an object."); if (m["registries"]?["quests"]?.GetValue<string>() != "src/registries/quests/" || m["registries"]?["dialogue"]?.GetValue<string>() != "src/registries/dialogue/") throw new InvalidOperationException("Manifest must use canonical narrative registry paths."); var q = JsonNode.Parse(qb)?.AsObject() ?? throw new JsonException("Quest source is not an object."); var d = JsonNode.Parse(db)?.AsObject() ?? throw new JsonException("Dialogue source is not an object."); if (Text(q, "schemaVersion") != "0.6.0" || Text(d, "schemaVersion") != "0.23.0") throw new InvalidOperationException("Quest 0.6.0 and dialogue 0.23.0 are required."); if (Directory.GetFiles(Path.GetDirectoryName(qp)!).Length != 1 || Directory.GetFiles(Path.GetDirectoryName(dp)!).Length != 1) throw new InvalidOperationException("One main.json document per narrative registry is required."); return (m, q, d, mb, qb, db); }
    private static string QuestPath(string r) => Path.Combine(r, "src", "registries", "quests", "main.json"); private static QuestConditionLoadResult FailLoad(string m) => new(false, m, [], [], []); private static QuestConditionPreview Fail(string m) => new(false, m, null, null, null); private static IReadOnlyList<JsonObject> Arr(JsonObject o, string k) => o[k] is JsonArray a ? a.OfType<JsonObject>().ToArray() : []; private static JsonArray Ensure(JsonObject o, string k) => o[k] as JsonArray ?? (JsonArray)(o[k] = new JsonArray()); private static string Text(JsonObject? o, string k) => o?[k]?.GetValue<string>() ?? ""; private static void Optional(JsonObject o, string k, string v) { var t = v.Trim(); if (t.Length > 0) o[k] = t; } private static string Slug(string v) { var s = v.Trim(); if (s.Length == 0 || s[0] is < 'a' or > 'z' || s.Any(c => !(char.IsAsciiLetterLower(c) || char.IsDigit(c)))) throw new InvalidOperationException("Condition slug must be lowercase ASCII alphanumeric."); return s; } private static string Json(JsonObject o) => o.ToJsonString(JsonOptions) + Environment.NewLine; private static string Hash(string v) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(v))).ToLowerInvariant();
}
