using System.IO;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using WastelandForge.Validation;

namespace WastelandForge.Desktop;

internal sealed record QuestStageResultChoice(string Id, string OwnerId, string Display);
internal sealed record QuestStageResultLoadResult(bool Success, string Message, IReadOnlyList<QuestStageResultChoice> Quests, IReadOnlyList<QuestStageResultChoice> Stages, IReadOnlyList<QuestStageResultChoice> Conditions);
internal sealed record QuestStageResultInput(string QuestId, string StageId, bool UseCondition, string ConditionId, string Slug, string Summary);
internal sealed record QuestStageResultPreview(bool Success, string Message, string? QuestJson, string? Declaration, string? Token);
internal sealed record QuestStageResultResult(bool Success, string Message);

internal static class QuestStageResultAuthoring
{
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };
    public static QuestStageResultLoadResult Load(string root) { try { var (_, qr, _, _, _, _) = Read(root); if (new ProjectValidationPipeline().Validate(root).HasErrors) return FailLoad("Project validation must pass before loading stage result choices."); var quests = Arr(qr, "quests"); var q = quests.Select(x => new QuestStageResultChoice(Text(x, "id"), Text(x, "id"), Text(x, "title"))).OrderBy(x => x.Id, StringComparer.Ordinal).ToArray(); var s = quests.SelectMany(owner => Arr(owner, "stages").Select(x => new QuestStageResultChoice(Text(x, "id"), Text(owner, "id"), $"{x["stage"]}: {Text(x, "title")}"))).OrderBy(x => x.Id, StringComparer.Ordinal).ToArray(); var c = quests.SelectMany(owner => Arr(owner, "conditions").Select(x => new QuestStageResultChoice(Text(x, "id"), Text(owner, "id"), string.IsNullOrWhiteSpace(Text(x, "title")) ? Text(x, "id") : Text(x, "title")))).OrderBy(x => x.Id, StringComparer.Ordinal).ToArray(); return q.Length == 0 ? FailLoad("Quest source has no quests.") : new(true, "Stage result choices loaded.", q, s, c); } catch (Exception ex) when (ex is IOException or JsonException or InvalidOperationException) { return FailLoad("Stage result load failed: " + ex.Message); } }
    public static QuestStageResultPreview Preview(string root, QuestStageResultInput input) { try { var (_, qr, _, mb, qb, db) = Read(root); if (new ProjectValidationPipeline().Validate(root).HasErrors) return Fail("Project validation must pass before preview."); var quest = Arr(qr, "quests").SingleOrDefault(x => Text(x, "id") == input.QuestId) ?? throw new InvalidOperationException("Selected quest no longer exists."); var stage = Arr(quest, "stages").SingleOrDefault(x => Text(x, "id") == input.StageId) ?? throw new InvalidOperationException("Selected stage does not belong to the selected quest."); if (input.UseCondition && !Arr(quest, "conditions").Any(x => Text(x, "id") == input.ConditionId)) throw new InvalidOperationException("Selected condition does not belong to the selected quest."); var id = input.StageId + ".result." + Slug(input.Slug); if (Arr(stage, "resultScripts").Any(x => Text(x, "id") == id)) throw new InvalidOperationException($"Stage result '{id}' already exists."); var result = new JsonObject { ["id"] = id, ["scriptType"] = "stageResult" }; if (input.UseCondition) result["conditionId"] = input.ConditionId; Optional(result, "summary", input.Summary); Ensure(stage, "resultScripts").Add(result); var proposal = Json(qr); return new(true, "Stage result intent preview ready.", proposal, result.ToJsonString(JsonOptions), Hash(mb + "\n" + qb + "\n" + db + "\n" + proposal)); } catch (Exception ex) when (ex is IOException or JsonException or InvalidOperationException) { return Fail("Stage result preview failed: " + ex.Message); } }
    public static QuestStageResultResult Append(string root, QuestStageResultInput input, string token) { var p = Preview(root, input); if (!p.Success || p.Token != token) return new(false, p.Success ? "Source, selection, or inputs changed; preview again." : p.Message); var path = QuestPath(root); var original = File.ReadAllBytes(path); try { File.WriteAllText(path, p.QuestJson!, new UTF8Encoding(false)); if (new ProjectValidationPipeline().Validate(root).HasErrors) { File.WriteAllBytes(path, original); return new(false, "Stage result failed validation; original source restored."); } return new(true, "Stage result intent appended and validated."); } catch (Exception ex) when (ex is IOException or UnauthorizedAccessException) { try { File.WriteAllBytes(path, original); } catch { } return new(false, "Stage result write failed; original source restored: " + ex.Message); } }
    private static (JsonObject Manifest, JsonObject Quest, JsonObject Dialogue, string ManifestBytes, string QuestBytes, string DialogueBytes) Read(string root) { var r = Path.GetFullPath(root); var mp = Path.Combine(r, "wastelandforge.json"); var qp = QuestPath(r); var dp = Path.Combine(r, "src", "registries", "dialogue", "main.json"); if (!File.Exists(mp) || !File.Exists(qp) || !File.Exists(dp)) throw new InvalidOperationException("Canonical manifest, quest main.json, and dialogue main.json are required."); var mb = File.ReadAllText(mp); var qb = File.ReadAllText(qp); var db = File.ReadAllText(dp); var m = JsonNode.Parse(mb)?.AsObject() ?? throw new JsonException("Manifest is not an object."); if (m["registries"]?["quests"]?.GetValue<string>() != "src/registries/quests/" || m["registries"]?["dialogue"]?.GetValue<string>() != "src/registries/dialogue/") throw new InvalidOperationException("Manifest must use canonical narrative registry paths."); var q = JsonNode.Parse(qb)?.AsObject() ?? throw new JsonException("Quest source is not an object."); var d = JsonNode.Parse(db)?.AsObject() ?? throw new JsonException("Dialogue source is not an object."); if (Text(q, "schemaVersion") != "0.6.0" || Text(d, "schemaVersion") != "0.23.0") throw new InvalidOperationException("Quest 0.6.0 and dialogue 0.23.0 are required."); if (Directory.GetFiles(Path.GetDirectoryName(qp)!).Length != 1 || Directory.GetFiles(Path.GetDirectoryName(dp)!).Length != 1) throw new InvalidOperationException("One main.json document per narrative registry is required."); return (m, q, d, mb, qb, db); }
    private static string QuestPath(string r) => Path.Combine(r, "src", "registries", "quests", "main.json"); private static QuestStageResultLoadResult FailLoad(string m) => new(false, m, [], [], []); private static QuestStageResultPreview Fail(string m) => new(false, m, null, null, null); private static IReadOnlyList<JsonObject> Arr(JsonObject o, string k) => o[k] is JsonArray a ? a.OfType<JsonObject>().ToArray() : []; private static JsonArray Ensure(JsonObject o, string k) => o[k] as JsonArray ?? (JsonArray)(o[k] = new JsonArray()); private static string Text(JsonObject? o, string k) => o?[k]?.GetValue<string>() ?? ""; private static void Optional(JsonObject o, string k, string v) { var t = v.Trim(); if (t.Length > 0) o[k] = t; } private static string Slug(string v) { var s = v.Trim(); if (s.Length == 0 || s[0] is < 'a' or > 'z' || s.Any(c => !(char.IsAsciiLetterLower(c) || char.IsDigit(c)))) throw new InvalidOperationException("Result slug must be lowercase ASCII alphanumeric."); return s; } private static string Json(JsonObject o) => o.ToJsonString(JsonOptions) + Environment.NewLine; private static string Hash(string v) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(v))).ToLowerInvariant();
}
